# jdbc.X
jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/snowman?nullNamePatternMatchesAll=true

jdbc.username=root
jdbc.password=Root@12345
jdbc.url=jdbc:mysql://localhost:3306/snowman?nullNamePatternMatchesAll=true

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
# validate | update | create | create-drop
hibernate.hbm2ddl.auto=validate

# Messaging - JMS
jms.brokerUrl=tcp://localhost:61616
