# jdbc.X
jdbc.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.url=jdbc:mysql://snowman-test.mysql.database.azure.com:3306/snowman?nullNamePatternMatchesAll=true

jdbc.username=${DB_USERNAME}
jdbc.password=${DB_PASSWORD}

# hibernate.X
hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
hibernate.show_sql=true
# validate | update | create | create-drop
hibernate.hbm2ddl.auto=validate

# Messaging - JMS
jms.brokerUrl=tcp://localhost:61616
